# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160822_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
